include:
  - front/.front-ci.yml
  - back/.back-ci.yml

stages:
  - install
  - test
  - build
  - staging
  - production

.ancre:
  image: node:22
  tags:
    - node
  rules: 
   - if: $CI_COMMIT_REF_NAME == "main"