npm_install:back:
  stage: install
  extends: 
    - .ancre
  cache:
    key: back-cache-$CI_COMMIT_REF_SLUG
    paths:
    - back/node_modules
    policy: pull-push
  script:
    - cd back
    - npm install

npm_unit_test:back:
  stage: test
  extends: 
   - .ancre
  cache:
    key: back-cache-$CI_COMMIT_REF_SLUG
    paths:
    - back/node_modules
    policy: pull
  script:
    - cd back
    - npm run test-unit

npm_functional_test:back:
  stage: test
  extends: 
    - .ancre
  cache:
    key: back-cache-$CI_COMMIT_REF_SLUG
    paths:
    - back/node_modules
    policy: pull
  script:
    - cd back
    - npm run test-functional


deploy_staging:back:
  stage: staging
  extends:
    - .ancre
  script: 
    - cd back
    - echo "deploy back to staging"

deploy_production:back:
  stage: production
  extends:
    - .ancre
  image: google/cloud-sdk:alpine
  script: 
    - cd back
    - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > gcloud-api-key.json
    - gcloud auth activate-service-account --key-file gcloud-api-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME .
    - gcloud run deploy $CLOUD_RUN_SERVICE_NAME --image gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME --region $GCP_REGION --platform managed --allow-unauthenticated
  when: manual