# --- CONFIGURATION DE BASE FRONT ---
.front_base:
  image: node:22
  tags:
    - node
  variables:
    APP_DIR: front
  before_script:
    - cd $APP_DIR
  cache:
    key: $APP_DIR-cache-$CI_COMMIT_REF_SLUG
    paths:
      - $APP_DIR/node_modules
    policy: pull
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      changes:
        - front/**/* # Ne lance le CI que si le front est modifié

npm_install:front:
  stage: install
  extends: 
    - .front_base
  cache:
    policy: pull-push
  script:
    - npm install

npm_unit_test:front:
  stage: test
  extends: 
    - .front_base
  script:
    - npm run test-unit

npm_functional_test:front:
  stage: test
  extends: 
    - .front_base
  script:
    - npm run test-functional

npm_build:front:
  stage: build
  extends:
    - .front_base
  script:
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - front/build

deploy_staging:front:
  stage: staging
  extends:
    - .front_base
  script:
    - echo "deploy front to staging"

deploy_production:front:
  stage: production
  extends:
    - .front_base
  script:
    - npx netlify-cli deploy --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    # On doit redéfinir la règle car on ajoute 'when: manual'
    - if: $CI_COMMIT_REF_NAME == "main"
      changes:
        - front/**/*
      when: manual
