npm_install:front:
  stage: install
  extends: 
    - .ancre
  cache:
    key: front-cache-$CI_COMMIT_REF_SLUG 
    paths:
    - front/node_modules
    policy: pull-push
  script:
    - cd front
    - npm install

npm_unit_test:front:
  stage: test
  extends: 
    - .ancre
  cache:
    key: front-cache-$CI_COMMIT_REF_SLUG 
    paths:
    - front/node_modules
    policy: pull
  script:
    - cd front
    - npm run test-unit

npm_functional_test:front:
  stage: test
  extends: 
    - .ancre
  cache:
    key: front-cache-$CI_COMMIT_REF_SLUG 
    paths:
    - front/node_modules
    policy: pull
  script:
    - cd front
    - npm run test-functional

npm_build:front:
  stage: build
  extends:
    - .ancre
  cache:
    key: front-cache-$CI_COMMIT_REF_SLUG 
    paths:
    - front/node_modules
    policy: pull
  script: 
    - cd front
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - front/build

deploy_staging:front:
  stage: staging
  extends:
    - .ancre
  script: 
    - cd front
    - echo "deploy front to staging"

deploy_production:front:
  stage: production
  extends:
    - .ancre
  script: 
    - cd front
    - npx netlify-cli deploy --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  when: manual