name: CI/CD Pipeline

on:
  push:
    branches:
      - tp-16-03
  pull_request:
    branches:
      - tp-16-03

jobs:
  buil:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout du commit
        uses: actions/checkout@v4
      
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'
    
      - name: Installation des dépendances
        run: npm install

      - name: Tests Unitaires
        run: npm run test-unit

      - name: Tests Fonctionnels
        run: npm run test-functional